### ISSUE TITLE
loadTranslations in getStaticProps doesn't get the selected namespace

### ISSUE THREAD

**Issue by CorVous** [JCQuintas/ni18n#36]
```
export const getStaticProps: GetStaticProps = async (props: any) => {
  return {
    props: {
      ...(await loadTranslations(ni18nConfig, props.locale, [
        'common',
      ]))
    },
  }
}
```

obtains the "translation" namespace instead even though I do not have "translation" defined as a namespace

**Comment by JCQuintas** [comment]
HI @CorVous, can you share your `ni18nConfig`?

You are seeing the `translation` namespace because we always return the `defaultNS` like `i18next` does, though this behaviour slightly changed in the recent `i18next>=21` versions, so I might need to revisit the logic to fix unwanted behaviours. For now, if you are using `common` as your `defaultNS` you can set that in your config as below and it should work.

```ts
const ni18nConfig = {
  defaultNS: 'common',
  supportedLngs: [..your-langs],
  ns: ['common', ...all-other-namespaces],
}
```

I hope this helps :)

**Comment by JCQuintas** [comment]
Hey @CorVous , were you able to fix the issue?
