### ISSUE TITLE
ES5 Support?

### ISSUE THREAD

**Issue by gambinish** [JCQuintas/ni18n#47]
Hi Jose,

Currently using this package to help translate a pretty big Next.js project. It's working really well so far, and it allows for client-side toggling between locale strings which was something that was difficult to accomplish with other solutions, without having to mutate the url string (something that was somewhat of a deal-breaker).

However, this Next.js project needs to support IE11 😩 . Specifically, the `appWithI18Next` function seems to only compile down to ES6 syntax (with arrow functions), which causes the app to break when running in IE:

![image (3)](https://user-images.githubusercontent.com/35090461/146243768-352ff2d0-e6f1-4fc8-9d8d-11a8f7a77005.png)

We are currently looking into solutions for doing some custom transipling down to ES5 with in the next.js config using https://www.npmjs.com/package/next-transpile-modules, or potentially even patching the library locally to allow for IE11 support. Unsure how this will end up but figured I should open up an issue anyway.

Wondering how you feel about this? Would you be willing/have time to help us with this, or if you would maybe be open to us creating a PR?

**Comment by JCQuintas** [comment]
Hi Nick, I'm glad that this package is working for you. That is one of the use cases I also missed when using different solutions. :)

Overall, since you already `have` to transpile down to `es5`, I would suggest you to use `next-transpile-modules` regardless so you don't have to set it up in case a future library is only available for more modern targets, which is starting to become more and more common, specially with MS stopping support for IE11.

With that said, I wouldn't have a problem with any PRs or changes to accomodate to your needs, since I believe a lot of developers will also have the same need in the near future.

We don't really use any bundlers, since our target is `nextjs` and it will always have a bundler there. So our code is pretty much the output of `tsc` and I suspect we would only need to change the target to `es5`.

I'll try this out when I've got some time later this week, but if you figure something out that will work for you, please open a PR and we can discuss there as well.

**Comment by gambinish** [comment]
Wow, thanks for the quick response!

Sure, we will work on trying to get a solution on our end as well, but would also very much appreciate it if you could tinker with the `es5` target as well (time permitting).

Will keep you posted here on our progress 🙏

**Comment by gambinish** [comment]
Quick update from our end. It looks like we were able to resolve this breaking bug on IE by adding in the `next-transpile-modules` and targeting `es5` as you suggested. Currently going through QA rounds, but testing locally and everything seemed to work fine.

Only minor issue was that we now get a console warning when spinning up the next.js app locally:

```
warn  - ./node_modules/ni18n/dist/esm/index.js
Anonymous arrow functions cause Fast Refresh to not preserve local component state.
Please add a name to your function, for example:

Before
export default () => <div />;

After
const Named = () => <div />;
export default Named;

A codemod is available to fix the most common cases: https://nextjs.link/codemod-ndc
```

Honestly this is nbd, as it doesn't block our internal release, but still thought I would post it here. Unsure if you feel like it's worth it to address this in the library or not since IE11 is "officially" unsupported (even if we often still need to keep things backwards compatible). Maybe just an update to the `README.md`?

**Comment by JCQuintas** [comment]
Hey @gambinish, sorry for the delay. But I've just published a small `release candidate` to the package by targeting `es5` when compiling typescript. 

If you could try changing the version in your `package.json` to `"ni18n": "^1.0.3-rc.0"` and letting me know if that solves you issue, then we can push for a release as soon as possible :)

**Comment by gambinish** [comment]
@JCQuintas no worries!

Just bumped our version locally to the `release candidate` you specified and I no longer see that console warning! Thank you so much 🙏 

Keep me posted, but this isn't super urgent on our end. We are currently trying to keep things as stable as possible during the holiday break, so since this isn't blocking our internal release we probably won't be making this change until after our teams get back.

So, no rush 😄 

Thanks again, and Happy Holidays!

**Comment by JCQuintas** [comment]
Hi @gambinish hope you had a good end of the year 🥳 

I expect the issue was solved on your part, did you find any other issues with the fix yet? If not I'll be publishing the changes to a minor release this week. :)

**Comment by gambinish** [comment]
Hey @JCQuintas same to you!

Everything else seems to be working as expected. Feel free to publish that minor release whenever you have time.

Thanks again!
